### ISSUE TITLE
Editor inside of Paper Programs

### ISSUE THREAD

**Issue by paulsonnentag** [pyxel-lab/pyxel-lab#3]
It would be nice to get away from the laptop and move the editing process to Paper Programs similar to Dynamicland:

<img width="1657" alt="screen shot 2018-05-03 at 18 10 35" src="https://user-images.githubusercontent.com/650540/39589018-521df6a4-4efd-11e8-83f5-edd8f28794d7.png">

## Summary
Our projector doesn't have a high enough resolution to project the editor onto paper. Alternatively, we could use an iPad to open the editor and then place a paper program around it to script the editor.
We could use the paper data to communicate between editor and paper program.

## Todo
- [ ] Extend editor to be controllable from paper programms
   - [ ] add optional URL parameter to specify the paper number from which the editor should read attributes
   - [ ] read selected paper from paper data
   - [ ] hide drop down
   - [ ] reload paper data in interval
- [ ] Build holder for iPad
    - [ ] add QR code with correct URL of the editor
- [ ] Write the driver program in Paper Programs
    - [ ] detect which paper is placed in front
    - [ ] set editor to program number

**Bonus**
- [ ] Use Laser to select programs
- [ ] Use Paper Programs keyboard instead connecting the Bluetooth keyboard with the iPad directly
